Add helm post-install hook to automate placement tagging in CouchDB nodes
apache/couchdb-helm pull request #66
Opened 2022-01-26 21:29 UTC by fsalazarh

#### What this PR does / why we need it:

In order to control shard distribution across CouchDB nodes is necessary tagging the nodes in the database `_nodes` with the "zone" attribute. https://docs.couchdb.org/en/stable/cluster/sharding.html#specifying-database-placement

This PR add a `post-install hook` that create a Job that automate the tagging of "zone" attribute, obtaining the info from node labels of kubernetes and the pods allocated on each node. For more information of the procedure itself, please refer to https://github.com/caligrafix/couchdb-autoscaler-placement-manager/blob/main/src/scripts.py

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

We consider that the better way to achieve this is through a configuration file, but currently this solution meets our needs so it's useful. We use this post-install hook in combination with Cluster Autoscaler and Vertical Pod Autoscaler, so this components are responsible for not schedule the pods in other zones after killing them for some reason (e.g. after VPA assigns new requests and limits values). 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.
- [x] Chart Version bumped
- [x] e2e tests pass
- [x] Variables are documented in the README.md
- [x] Chart tgz added to /docs and index updated

2022-01-27 02:44 UTC, kocolosk requested changes
Thanks for this contribution! I'd like to see if a couple of the added parameters can be eliminated to minimize the chance of user error. But this is a nice convenience.

2022-01-27 12:27 UTC, fsalazarh commented on couchdb/README.md
> +| `placementConfig.namespace`          | couchdb                                |
Yes, that is the purpose of the namespace variable in the script. I change this variable to use `{{ .Release.Namespace }}`

2022-01-27 12:32 UTC, fsalazarh commented on couchdb/README.md
> +| `placementConfig.couchdbPort`        | 5984                                   |
In principle no, so I'm going to change it to use `service.externalPort`.

2022-01-27 12:40 UTC, fsalazarh commented on couchdb/templates/placementmanager.yaml
> +          - name: EKS_NAMESPACE
Done.

2022-01-27 12:45 UTC, fsalazarh commented on couchdb/templates/placementmanager.yaml
> +
Done

2022-01-27 14:57 UTC, fsalazarh commented on couchdb/values.yaml
> +    tag: latest
Thanks for this suggestion!, I added a semantic version for placement manager repo.

2022-01-27 15:10 UTC, fsalazarh reviewed
I update the code with all suggestions, thanks @kocolosk for review and please review again.

2022-01-30 01:45 UTC, merged

2022-01-30 01:48 UTC, kocolosk commented
LGTM, thanks!